### ISSUE TITLE
FT6236 In vain

### ISSUE THREAD

**Issue by yel-best** [track-tech/ESP32C3-st7789v-ft6236u-arduino-touch-OpenSource#1]
Hi，

My Env:
use LVGL 8.3
use ILI9488 + FT6236 touch

我使用跟你一样的方式获取触摸屏点击坐标`#include <FT6236.h>` 但是当我合并LVGL后会出现屏幕不显示UI，但是点击屏幕会有X & Y轴坐标出现，当我不使用 `if (!ts.begin(40))`的时候屏幕就能出现LVGL UI但是不能出现X&Y轴坐标，不知道什么原因导致的奇怪问题，我想咨询一下，你这边是否有遇到过类似的情况，有什么办法解决吗？

另外想问一下，好像 `if (!ts.begin(40)) `需要指定一个 SDA, & SCL，我看你这里没有使用，你是用那两个GPIO呢？

非常感谢，thanks

**Comment by track-tech** [comment]
抱歉之前一直在忙，没有顾得上回复，这个问题我也不是很清楚，你可以去这里问一下，移植底层驱动的作者是 @Sparkle
https://github.com/zanjie1999/esp32-st7789v-ft6236u-arduino

**Comment by track-tech** [comment]
抱歉之前一直在忙，没有顾得上回复，这个问题我也不是很清楚，你可以去这里问一下，移植底层驱动的作者是 
@Sparkle
下面是她的项目：
https://github.com/zanjie1999/esp32-st7789v-ft6236u-arduino
